PUBLIC_KEY_BACKUP_MONGO_AWS: ${ssm:PUBLIC_KEY_BACKUP_MONGO_AWS}
PRIVATE_KEY_BACKUP_MONGO_AWS: ${ssm:PRIVATE_KEY_BACKUP_MONGO_AWS}
PRIVATE_SUBNET_1: subnet-2312312d5f0a3a
PRIVATE_SUBNET_2: subnet-0a78qewcasd979f4a
SECURITY_GROUP_ID: sg-0475asdsadscc