PUBLIC_KEY_BACKUP_MONGO_AWS: ${ssm:PUBLIC_KEY_BACKUP_MONGO_AWS}
PRIVATE_KEY_BACKUP_MONGO_AWS: ${ssm:PRIVATE_KEY_BACKUP_MONGO_AWS}
PRIVATE_SUBNET_1: subnet-0ebd4ddfa425f0a3a
PRIVATE_SUBNET_2: subnet-0a78c2d6d0a979f4a
SECURITY_GROUP_ID: sg-047559b8131f3b2cc