functionbeat.provider.aws.endpoint: "s3.amazonaws.com"
functionbeat.provider.aws.deploy_bucket: "elk-condolivre-prod"
functionbeat.provider.aws.functions:
  - name: elkcondo
    enabled: true
    type: cloudwatch_logs
    description: "Função lambda para capturar log das funções da conta de produção condo"
    memory_size: 128MiB
    fields:
    env: production
    triggers:
      - log_group_name: /aws/lambda/condo-loan-asyc-production-address-ocr-finished
      - log_group_name: /aws/lambda/condo-loan-asyc-production-banker-document-update
      - log_group_name: /aws/lambda/condo-loan-asyc-production-check-expired-order
      - log_group_name: /aws/lambda/condo-loan-asyc-production-company-moved
      - log_group_name: /aws/lambda/condo-loan-asyc-production-employee-rescision
      - log_group_name: /aws/lambda/condo-loan-asyc-production-export-bankslip-file
      - log_group_name: /aws/lambda/condo-loan-asyc-production-export-bankslip-file-on-adm
      - log_group_name: /aws/lambda/condo-loan-asyc-production-generate-bankslip-on-condo
      - log_group_name: /aws/lambda/condo-loan-asyc-production-generate-insurance
      - log_group_name: /aws/lambda/condo-loan-asyc-production-id-back-ocr-finished
      - log_group_name: /aws/lambda/condo-loan-asyc-production-id-front-ocr-finished
      - log_group_name: /aws/lambda/condo-loan-asyc-production-notify-external-lead
      - log_group_name: /aws/lambda/condo-loan-asyc-production-notify-pending-approval
      - log_group_name: /aws/lambda/condo-loan-asyc-production-payslip-ocr-finished
      - log_group_name: /aws/lambda/condo-loan-asyc-production-process-bankslip-on-adm
      - log_group_name: /aws/lambda/condo-loan-asyc-production-process-bankslips
      - log_group_name: /aws/lambda/condo-loan-asyc-production-process-conciliation
      - log_group_name: /aws/lambda/condo-loan-asyc-production-process-conciliation-on-adm
      - log_group_name: /aws/lambda/condo-loan-asyc-production-process-individual-bankslip-on-adm
      - log_group_name: /aws/lambda/condo-loan-asyc-production-process-settlements
      - log_group_name: /aws/lambda/condo-loan-asyc-production-process-usebens-conciliation
      - log_group_name: /aws/lambda/condo-loan-asyc-production-request-ccbs
      - log_group_name: /aws/lambda/condo-loan-asyc-production-send-pending-approval
      - log_group_name: /aws/lambda/condo-loan-asyc-production-send-usebens-conciliation
      - log_group_name: /aws/lambda/condo-loan-asyc-production-update-bankslip
      - log_group_name: /aws/lambda/condo-loan-asyc-production-update-bankslip-metadata
      - log_group_name: /aws/lambda/condo-loan-asyc-production-update-loan

setup.template.name: "production"
setup.template.pattern: "production"
setup.template.settings:
setup.kibana:

cloud.id: "ELK_CondoLivre:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyQ5Y2ExOGQ0Nzk2YzY0MmYyOWU5ZTczY2E1ZTcwYjgwZSQ5YWIyNDFiMjBhNzg0MTMwOGM2ZTJhNGQ4ODZlMzUwYQ=="
cloud.auth: "elastic:H8rE2xkLwEuT8VZTueStdQbL"

output.elasticsearch:  
  hosts: ["localhost:9200"]
  index: "production"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~ 
