name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled
  push:

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@v1
        with:
          github_token: "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"