name: Deploy Elasticsearch

on:
  push:
    tags:
      - elkondo*

jobs:
  deploy-elastic-search-dev:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: dev-${{ github.event.repository.name }}
      CLUSTER: dev-cluster
      ENVIRONMENT: dev

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}
  
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes

      - name: Prepare files
        run: | 
          chmod +x elkondo_prepare.sh
          ./elkondo_prepare.sh -d prime-numbers
          ls -R temp
          cat temp/cara-c/file.txt

      - name: Generate files
        run: | 
          chmod +x elkondo_generate.sh
          cd prime-numbers
          pwd
          ls
          #./elkondo_generate.sh elk-condolivre-prod production ELK_CondoLivre:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyQ5Y2ExOGQ0Nzk2YzY0MmYyOWU5ZTczY2E1ZTcwYjgwZSQ5YWIyNDFiMjBhNzg0MTMwOGM2ZTJhNGQ4ODZlMzUwYQ== elastic:H8rE2xkLwEuT8VZTueStdQbL


      - name: Deploy Elasticsearch DEV
        run:  |
          curl -L -O https://artifacts.elastic.co/downloads/beats/functionbeat/functionbeat-8.3.2-linux-x86_64.tar.gz
          tar xzvf functionbeat-8.3.2-linux-x86_64.tar.gz
          cd functionbeat-8.3.2-linux-x86_64
          ls
          chmod +x functionbeat
          ./functionbeat version

  # deploy-elastic-search-stg:
  #   runs-on: ubuntu-latest
  #   env:
  #     SERVICE_NAME: dev-${{ github.event.repository.name }}
  #     CLUSTER: dev-cluster
  #     ENVIRONMENT: dev

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
  #         aws-region: ${{ secrets.AWS_REGION_STG }}

  #     - name: Deploy Elasticsearch STG
  #       run:  |
  #         echo "STG"
  #         aws s3 ls

  # deploy-elastic-search-prod:
  #   runs-on: ubuntu-latest
  #   env:
  #     SERVICE_NAME: dev-${{ github.event.repository.name }}
  #     CLUSTER: dev-cluster
  #     ENVIRONMENT: dev

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
  #         aws-region: ${{ secrets.AWS_REGION_PROD }}

  #     - name: Deploy Elasticsearch PROD
  #       run:  |
  #         echo "PROD"
  #         aws s3 ls