name: Deploy Serverless Backup Mongo

on:
  push:
    tags:
      - mongo*

jobs:
  deploy-serverless-bkp-mongo-prod:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS Authentication
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID_PROD }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

      - name: Deploy AWS Lambda functions
        run: serverless deploy --stage production --region ${{ secrets.AWS_REGION_PROD }}